<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use RuntimeException;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        if (!app()->environment(['local', 'testing'])) {
            throw new RuntimeException(
                'Demo data may only be seeded in the local or testing environment.'
            );
        }

        // UserSeeder is internally idempotent and creates any missing demo role accounts.
        $this->call(UserSeeder::class);

        // OTP records are transient security data and must be generated by the authentication flow.
        $this->callIfEmpty('patients', PatientSeeder::class);
        $this->callIfEmpty('tests', TestSeeder::class);
        $this->callIfEmpty('insurance_companies', InsuranceCompanySeeder::class);
        $this->callIfEmpty('coverage_rules', CoverageRuleSeeder::class);
        $this->callIfEmpty('test_requests', TestRequestSeeder::class);
        $this->callIfEmpty('test_request_items', TestRequestItemSeeder::class);
        $this->callIfEmpty('samples', SampleSeeder::class);
        $this->callIfEmpty('test_results', TestResultSeeder::class);
        $this->callIfEmpty('medical_reports', MedicalReportSeeder::class);
        $this->callIfEmpty('invoices', InvoiceSeeder::class);
        $this->callIfEmpty('invoice_items', InvoiceItemSeeder::class);
        $this->callIfEmpty('payments', PaymentSeeder::class);
        $this->callIfEmpty('reagents', ReagentSeeder::class);
        $this->callIfEmpty('reagent_lots', ReagentLotSeeder::class);
        $this->callIfEmpty('reagent_test', ReagentTestSeeder::class);
        $this->callIfEmpty('stock_transactions', StockTransactionSeeder::class);
        $this->callIfEmpty('notifications', NotificationSeeder::class);
        $this->callIfEmpty('audit_logs', AuditLogSeeder::class);
        $this->callIfEmpty('system_settings', SystemSettingSeeder::class);
    }

    private function callIfEmpty(string $table, string $seeder): void
    {
        if (DB::table($table)->exists()) {
            $this->command?->line("Skipping {$seeder}: {$table} already contains data.");

            return;
        }

        $this->call($seeder);
    }
}
